// AUTO-GENERATED by scripts/generate-plasmic-tokens.ts — do not edit.
// Regenerated on every dev/build start from beamPreset (see vite.config.ts).
import { registerToken } from "@plasmicapp/react-web/lib/host";

const beamTokens = [
  {
    "name": "colors.sunbeam.orange",
    "value": "var(--colors-sunbeam.orange)",
    "type": "color",
    "displayName": "Beam / Sunbeam / Orange"
  },
  {
    "name": "colors.sunbeam.flame",
    "value": "var(--colors-sunbeam.flame)",
    "type": "color",
    "displayName": "Beam / Sunbeam / Flame"
  },
  {
    "name": "colors.beam.orange",
    "value": "var(--colors-beam.orange)",
    "type": "color",
    "displayName": "Beam / Beam / Orange"
  },
  {
    "name": "colors.sunshine.900",
    "value": "var(--colors-sunshine.900)",
    "type": "color",
    "displayName": "Beam / Sunshine / 900"
  },
  {
    "name": "colors.sunshine.700",
    "value": "var(--colors-sunshine.700)",
    "type": "color",
    "displayName": "Beam / Sunshine / 700"
  },
  {
    "name": "colors.sunshine.500",
    "value": "var(--colors-sunshine.500)",
    "type": "color",
    "displayName": "Beam / Sunshine / 500"
  },
  {
    "name": "colors.sunshine.300",
    "value": "var(--colors-sunshine.300)",
    "type": "color",
    "displayName": "Beam / Sunshine / 300"
  },
  {
    "name": "colors.sunshine.50",
    "value": "var(--colors-sunshine.50)",
    "type": "color",
    "displayName": "Beam / Sunshine / 50"
  },
  {
    "name": "colors.sunshine.35",
    "value": "var(--colors-sunshine.35)",
    "type": "color",
    "displayName": "Beam / Sunshine / 35"
  },
  {
    "name": "colors.sunshine.25",
    "value": "var(--colors-sunshine.25)",
    "type": "color",
    "displayName": "Beam / Sunshine / 25"
  },
  {
    "name": "colors.beam.gold",
    "value": "var(--colors-beam.gold)",
    "type": "color",
    "displayName": "Beam / Beam / Gold"
  },
  {
    "name": "colors.bright.yellow",
    "value": "var(--colors-bright.yellow)",
    "type": "color",
    "displayName": "Beam / Bright / Yellow"
  },
  {
    "name": "colors.warm.ivory",
    "value": "var(--colors-warm.ivory)",
    "type": "color",
    "displayName": "Beam / Warm / Ivory"
  },
  {
    "name": "colors.cream",
    "value": "var(--colors-cream)",
    "type": "color",
    "displayName": "Beam / Cream"
  },
  {
    "name": "colors.sunbeam.black",
    "value": "var(--colors-sunbeam.black)",
    "type": "color",
    "displayName": "Beam / Sunbeam / Black"
  },
  {
    "name": "colors.white",
    "value": "var(--colors-white)",
    "type": "color",
    "displayName": "Beam / White"
  },
  {
    "name": "colors.card.dark",
    "value": "var(--colors-card.dark)",
    "type": "color",
    "displayName": "Beam / Card / Dark"
  },
  {
    "name": "colors.code.activePill",
    "value": "var(--colors-code.active-pill)",
    "type": "color",
    "displayName": "Beam / Code / ActivePill"
  },
  {
    "name": "colors.code.text",
    "value": "var(--colors-code.text)",
    "type": "color",
    "displayName": "Beam / Code / Text"
  },
  {
    "name": "colors.code.success",
    "value": "var(--colors-code.success)",
    "type": "color",
    "displayName": "Beam / Code / Success"
  },
  {
    "name": "colors.syn.keyword",
    "value": "var(--colors-syn.keyword)",
    "type": "color",
    "displayName": "Beam / Syn / Keyword"
  },
  {
    "name": "colors.syn.fn",
    "value": "var(--colors-syn.fn)",
    "type": "color",
    "displayName": "Beam / Syn / Fn"
  },
  {
    "name": "colors.syn.string",
    "value": "var(--colors-syn.string)",
    "type": "color",
    "displayName": "Beam / Syn / String"
  },
  {
    "name": "colors.syn.prop",
    "value": "var(--colors-syn.prop)",
    "type": "color",
    "displayName": "Beam / Syn / Prop"
  },
  {
    "name": "colors.syn.number",
    "value": "var(--colors-syn.number)",
    "type": "color",
    "displayName": "Beam / Syn / Number"
  },
  {
    "name": "colors.syn.builtin",
    "value": "var(--colors-syn.builtin)",
    "type": "color",
    "displayName": "Beam / Syn / Builtin"
  },
  {
    "name": "colors.border.warm",
    "value": "var(--colors-border.warm)",
    "type": "color",
    "displayName": "Beam / Border / Warm"
  },
  {
    "name": "colors.border.warmSubtle",
    "value": "var(--colors-border.warm-subtle)",
    "type": "color",
    "displayName": "Beam / Border / WarmSubtle"
  },
  {
    "name": "colors.border.warmDark",
    "value": "var(--colors-border.warm-dark)",
    "type": "color",
    "displayName": "Beam / Border / WarmDark"
  },
  {
    "name": "colors.accent.06",
    "value": "var(--colors-accent.06)",
    "type": "color",
    "displayName": "Beam / Accent / 06"
  },
  {
    "name": "colors.accent.08",
    "value": "var(--colors-accent.08)",
    "type": "color",
    "displayName": "Beam / Accent / 08"
  },
  {
    "name": "colors.accent.10",
    "value": "var(--colors-accent.10)",
    "type": "color",
    "displayName": "Beam / Accent / 10"
  },
  {
    "name": "colors.accent.12",
    "value": "var(--colors-accent.12)",
    "type": "color",
    "displayName": "Beam / Accent / 12"
  },
  {
    "name": "colors.accent.15",
    "value": "var(--colors-accent.15)",
    "type": "color",
    "displayName": "Beam / Accent / 15"
  },
  {
    "name": "colors.accent.20",
    "value": "var(--colors-accent.20)",
    "type": "color",
    "displayName": "Beam / Accent / 20"
  },
  {
    "name": "colors.accent.30",
    "value": "var(--colors-accent.30)",
    "type": "color",
    "displayName": "Beam / Accent / 30"
  },
  {
    "name": "colors.accent.40",
    "value": "var(--colors-accent.40)",
    "type": "color",
    "displayName": "Beam / Accent / 40"
  },
  {
    "name": "colors.chrome.03",
    "value": "var(--colors-chrome.03)",
    "type": "color",
    "displayName": "Beam / Chrome / 03"
  },
  {
    "name": "colors.chrome.05",
    "value": "var(--colors-chrome.05)",
    "type": "color",
    "displayName": "Beam / Chrome / 05"
  },
  {
    "name": "colors.chrome.06",
    "value": "var(--colors-chrome.06)",
    "type": "color",
    "displayName": "Beam / Chrome / 06"
  },
  {
    "name": "colors.chrome.10",
    "value": "var(--colors-chrome.10)",
    "type": "color",
    "displayName": "Beam / Chrome / 10"
  },
  {
    "name": "colors.chrome.30",
    "value": "var(--colors-chrome.30)",
    "type": "color",
    "displayName": "Beam / Chrome / 30"
  },
  {
    "name": "colors.chrome.35",
    "value": "var(--colors-chrome.35)",
    "type": "color",
    "displayName": "Beam / Chrome / 35"
  },
  {
    "name": "colors.chrome.40",
    "value": "var(--colors-chrome.40)",
    "type": "color",
    "displayName": "Beam / Chrome / 40"
  },
  {
    "name": "colors.chrome.50",
    "value": "var(--colors-chrome.50)",
    "type": "color",
    "displayName": "Beam / Chrome / 50"
  },
  {
    "name": "colors.chrome.60",
    "value": "var(--colors-chrome.60)",
    "type": "color",
    "displayName": "Beam / Chrome / 60"
  },
  {
    "name": "colors.chrome.70",
    "value": "var(--colors-chrome.70)",
    "type": "color",
    "displayName": "Beam / Chrome / 70"
  },
  {
    "name": "colors.chrome.90",
    "value": "var(--colors-chrome.90)",
    "type": "color",
    "displayName": "Beam / Chrome / 90"
  },
  {
    "name": "colors.warm.04",
    "value": "var(--colors-warm.04)",
    "type": "color",
    "displayName": "Beam / Warm / 04"
  },
  {
    "name": "colors.warm.10",
    "value": "var(--colors-warm.10)",
    "type": "color",
    "displayName": "Beam / Warm / 10"
  },
  {
    "name": "colors.warm.25",
    "value": "var(--colors-warm.25)",
    "type": "color",
    "displayName": "Beam / Warm / 25"
  },
  {
    "name": "colors.warm.30",
    "value": "var(--colors-warm.30)",
    "type": "color",
    "displayName": "Beam / Warm / 30"
  },
  {
    "name": "colors.warm.40",
    "value": "var(--colors-warm.40)",
    "type": "color",
    "displayName": "Beam / Warm / 40"
  },
  {
    "name": "colors.creamA.30",
    "value": "var(--colors-cream-a.30)",
    "type": "color",
    "displayName": "Beam / CreamA / 30"
  },
  {
    "name": "colors.ivory.30",
    "value": "var(--colors-ivory.30)",
    "type": "color",
    "displayName": "Beam / Ivory / 30"
  },
  {
    "name": "colors.ivory.50",
    "value": "var(--colors-ivory.50)",
    "type": "color",
    "displayName": "Beam / Ivory / 50"
  },
  {
    "name": "colors.scrim.45",
    "value": "var(--colors-scrim.45)",
    "type": "color",
    "displayName": "Beam / Scrim / 45"
  },
  {
    "name": "colors.scrim.50",
    "value": "var(--colors-scrim.50)",
    "type": "color",
    "displayName": "Beam / Scrim / 50"
  },
  {
    "name": "colors.scrim.55",
    "value": "var(--colors-scrim.55)",
    "type": "color",
    "displayName": "Beam / Scrim / 55"
  },
  {
    "name": "colors.scrim.60",
    "value": "var(--colors-scrim.60)",
    "type": "color",
    "displayName": "Beam / Scrim / 60"
  },
  {
    "name": "colors.scrim.85",
    "value": "var(--colors-scrim.85)",
    "type": "color",
    "displayName": "Beam / Scrim / 85"
  },
  {
    "name": "colors.grid.06",
    "value": "var(--colors-grid.06)",
    "type": "color",
    "displayName": "Beam / Grid / 06"
  },
  {
    "name": "colors.grid.15",
    "value": "var(--colors-grid.15)",
    "type": "color",
    "displayName": "Beam / Grid / 15"
  },
  {
    "name": "colors.grid.20",
    "value": "var(--colors-grid.20)",
    "type": "color",
    "displayName": "Beam / Grid / 20"
  },
  {
    "name": "colors.diff.add.bg",
    "value": "var(--colors-diff.add.bg)",
    "type": "color",
    "displayName": "Beam / Diff / Add / Bg"
  },
  {
    "name": "colors.diff.add.emphasis",
    "value": "var(--colors-diff.add.emphasis)",
    "type": "color",
    "displayName": "Beam / Diff / Add / Emphasis"
  },
  {
    "name": "colors.diff.del.bg",
    "value": "var(--colors-diff.del.bg)",
    "type": "color",
    "displayName": "Beam / Diff / Del / Bg"
  },
  {
    "name": "colors.diff.del.emphasis",
    "value": "var(--colors-diff.del.emphasis)",
    "type": "color",
    "displayName": "Beam / Diff / Del / Emphasis"
  },
  {
    "name": "colors.slate.05",
    "value": "var(--colors-slate.05)",
    "type": "color",
    "displayName": "Beam / Slate / 05"
  },
  {
    "name": "colors.slate.08",
    "value": "var(--colors-slate.08)",
    "type": "color",
    "displayName": "Beam / Slate / 08"
  },
  {
    "name": "colors.slate.10",
    "value": "var(--colors-slate.10)",
    "type": "color",
    "displayName": "Beam / Slate / 10"
  },
  {
    "name": "colors.slate.15",
    "value": "var(--colors-slate.15)",
    "type": "color",
    "displayName": "Beam / Slate / 15"
  },
  {
    "name": "fonts.heading",
    "value": "var(--fonts-heading)",
    "type": "font-family",
    "displayName": "Beam / Font family / heading"
  },
  {
    "name": "fonts.body",
    "value": "var(--fonts-body)",
    "type": "font-family",
    "displayName": "Beam / Font family / body"
  },
  {
    "name": "fonts.mono",
    "value": "var(--fonts-mono)",
    "type": "font-family",
    "displayName": "Beam / Font family / mono"
  },
  {
    "name": "fontSizes.8",
    "value": "var(--font-sizes-8)",
    "type": "font-size",
    "displayName": "Beam / Font size / 8"
  },
  {
    "name": "fontSizes.9",
    "value": "var(--font-sizes-9)",
    "type": "font-size",
    "displayName": "Beam / Font size / 9"
  },
  {
    "name": "fontSizes.11",
    "value": "var(--font-sizes-11)",
    "type": "font-size",
    "displayName": "Beam / Font size / 11"
  },
  {
    "name": "fontSizes.13",
    "value": "var(--font-sizes-13)",
    "type": "font-size",
    "displayName": "Beam / Font size / 13"
  },
  {
    "name": "fontSizes.15",
    "value": "var(--font-sizes-15)",
    "type": "font-size",
    "displayName": "Beam / Font size / 15"
  },
  {
    "name": "fontSizes.36",
    "value": "var(--font-sizes-36)",
    "type": "font-size",
    "displayName": "Beam / Font size / 36"
  },
  {
    "name": "fontSizes.40",
    "value": "var(--font-sizes-40)",
    "type": "font-size",
    "displayName": "Beam / Font size / 40"
  },
  {
    "name": "fontSizes.2xs",
    "value": "var(--font-sizes-2xs)",
    "type": "font-size",
    "displayName": "Beam / Font size / 2xs"
  },
  {
    "name": "fontSizes.xs",
    "value": "var(--font-sizes-xs)",
    "type": "font-size",
    "displayName": "Beam / Font size / xs"
  },
  {
    "name": "fontSizes.sm",
    "value": "var(--font-sizes-sm)",
    "type": "font-size",
    "displayName": "Beam / Font size / sm"
  },
  {
    "name": "fontSizes.md",
    "value": "var(--font-sizes-md)",
    "type": "font-size",
    "displayName": "Beam / Font size / md"
  },
  {
    "name": "fontSizes.lg",
    "value": "var(--font-sizes-lg)",
    "type": "font-size",
    "displayName": "Beam / Font size / lg"
  },
  {
    "name": "fontSizes.xl",
    "value": "var(--font-sizes-xl)",
    "type": "font-size",
    "displayName": "Beam / Font size / xl"
  },
  {
    "name": "fontSizes.2xl",
    "value": "var(--font-sizes-2xl)",
    "type": "font-size",
    "displayName": "Beam / Font size / 2xl"
  },
  {
    "name": "fontSizes.3xl",
    "value": "var(--font-sizes-3xl)",
    "type": "font-size",
    "displayName": "Beam / Font size / 3xl"
  },
  {
    "name": "fontSizes.4xl",
    "value": "var(--font-sizes-4xl)",
    "type": "font-size",
    "displayName": "Beam / Font size / 4xl"
  },
  {
    "name": "fontSizes.5xl",
    "value": "var(--font-sizes-5xl)",
    "type": "font-size",
    "displayName": "Beam / Font size / 5xl"
  },
  {
    "name": "fontSizes.6xl",
    "value": "var(--font-sizes-6xl)",
    "type": "font-size",
    "displayName": "Beam / Font size / 6xl"
  },
  {
    "name": "fontSizes.9.5",
    "value": "var(--font-sizes-9.5)",
    "type": "font-size",
    "displayName": "Beam / Font size / 9-5"
  },
  {
    "name": "fontSizes.10.5",
    "value": "var(--font-sizes-10.5)",
    "type": "font-size",
    "displayName": "Beam / Font size / 10-5"
  },
  {
    "name": "fontSizes.13.5",
    "value": "var(--font-sizes-13.5)",
    "type": "font-size",
    "displayName": "Beam / Font size / 13-5"
  },
  {
    "name": "spacing.0",
    "value": "var(--spacing-0)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 0"
  },
  {
    "name": "spacing.1",
    "value": "var(--spacing-1)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 1"
  },
  {
    "name": "spacing.2",
    "value": "var(--spacing-2)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 2"
  },
  {
    "name": "spacing.3",
    "value": "var(--spacing-3)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 3"
  },
  {
    "name": "spacing.4",
    "value": "var(--spacing-4)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 4"
  },
  {
    "name": "spacing.5",
    "value": "var(--spacing-5)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 5"
  },
  {
    "name": "spacing.6",
    "value": "var(--spacing-6)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 6"
  },
  {
    "name": "spacing.7",
    "value": "var(--spacing-7)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 7"
  },
  {
    "name": "spacing.8",
    "value": "var(--spacing-8)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 8"
  },
  {
    "name": "spacing.9",
    "value": "var(--spacing-9)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 9"
  },
  {
    "name": "spacing.10",
    "value": "var(--spacing-10)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 10"
  },
  {
    "name": "spacing.12",
    "value": "var(--spacing-12)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 12"
  },
  {
    "name": "spacing.14",
    "value": "var(--spacing-14)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 14"
  },
  {
    "name": "spacing.15",
    "value": "var(--spacing-15)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 15"
  },
  {
    "name": "spacing.16",
    "value": "var(--spacing-16)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 16"
  },
  {
    "name": "spacing.20",
    "value": "var(--spacing-20)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 20"
  },
  {
    "name": "spacing.24",
    "value": "var(--spacing-24)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 24"
  },
  {
    "name": "spacing.25",
    "value": "var(--spacing-25)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 25"
  },
  {
    "name": "spacing.28",
    "value": "var(--spacing-28)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 28"
  },
  {
    "name": "spacing.30",
    "value": "var(--spacing-30)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 30"
  },
  {
    "name": "spacing.32",
    "value": "var(--spacing-32)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 32"
  },
  {
    "name": "spacing.36",
    "value": "var(--spacing-36)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 36"
  },
  {
    "name": "spacing.40",
    "value": "var(--spacing-40)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 40"
  },
  {
    "name": "spacing.44",
    "value": "var(--spacing-44)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 44"
  },
  {
    "name": "spacing.45",
    "value": "var(--spacing-45)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 45"
  },
  {
    "name": "spacing.48",
    "value": "var(--spacing-48)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 48"
  },
  {
    "name": "spacing.50",
    "value": "var(--spacing-50)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 50"
  },
  {
    "name": "spacing.52",
    "value": "var(--spacing-52)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 52"
  },
  {
    "name": "spacing.56",
    "value": "var(--spacing-56)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 56"
  },
  {
    "name": "spacing.60",
    "value": "var(--spacing-60)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 60"
  },
  {
    "name": "spacing.64",
    "value": "var(--spacing-64)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 64"
  },
  {
    "name": "spacing.65",
    "value": "var(--spacing-65)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 65"
  },
  {
    "name": "spacing.72",
    "value": "var(--spacing-72)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 72"
  },
  {
    "name": "spacing.74",
    "value": "var(--spacing-74)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 74"
  },
  {
    "name": "spacing.75",
    "value": "var(--spacing-75)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 75"
  },
  {
    "name": "spacing.80",
    "value": "var(--spacing-80)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 80"
  },
  {
    "name": "spacing.96",
    "value": "var(--spacing-96)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 96"
  },
  {
    "name": "spacing.0.25",
    "value": "var(--spacing-0.25)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 0-25"
  },
  {
    "name": "spacing.0.5",
    "value": "var(--spacing-0.5)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 0-5"
  },
  {
    "name": "spacing.0.75",
    "value": "var(--spacing-0.75)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 0-75"
  },
  {
    "name": "spacing.1.25",
    "value": "var(--spacing-1.25)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 1-25"
  },
  {
    "name": "spacing.1.5",
    "value": "var(--spacing-1.5)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 1-5"
  },
  {
    "name": "spacing.1.75",
    "value": "var(--spacing-1.75)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 1-75"
  },
  {
    "name": "spacing.2.25",
    "value": "var(--spacing-2.25)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 2-25"
  },
  {
    "name": "spacing.2.5",
    "value": "var(--spacing-2.5)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 2-5"
  },
  {
    "name": "spacing.3.5",
    "value": "var(--spacing-3.5)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 3-5"
  },
  {
    "name": "spacing.4.5",
    "value": "var(--spacing-4.5)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 4-5"
  },
  {
    "name": "spacing.5.5",
    "value": "var(--spacing-5.5)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 5-5"
  },
  {
    "name": "spacing.7.5",
    "value": "var(--spacing-7.5)",
    "type": "spacing",
    "displayName": "Beam / Spacing / 7-5"
  },
  {
    "name": "sizes.0",
    "value": "var(--sizes-0)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 0"
  },
  {
    "name": "sizes.1",
    "value": "var(--sizes-1)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 1"
  },
  {
    "name": "sizes.2",
    "value": "var(--sizes-2)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 2"
  },
  {
    "name": "sizes.3",
    "value": "var(--sizes-3)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 3"
  },
  {
    "name": "sizes.4",
    "value": "var(--sizes-4)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 4"
  },
  {
    "name": "sizes.5",
    "value": "var(--sizes-5)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 5"
  },
  {
    "name": "sizes.6",
    "value": "var(--sizes-6)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 6"
  },
  {
    "name": "sizes.7",
    "value": "var(--sizes-7)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 7"
  },
  {
    "name": "sizes.8",
    "value": "var(--sizes-8)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 8"
  },
  {
    "name": "sizes.9",
    "value": "var(--sizes-9)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 9"
  },
  {
    "name": "sizes.10",
    "value": "var(--sizes-10)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 10"
  },
  {
    "name": "sizes.12",
    "value": "var(--sizes-12)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 12"
  },
  {
    "name": "sizes.14",
    "value": "var(--sizes-14)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 14"
  },
  {
    "name": "sizes.15",
    "value": "var(--sizes-15)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 15"
  },
  {
    "name": "sizes.16",
    "value": "var(--sizes-16)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 16"
  },
  {
    "name": "sizes.20",
    "value": "var(--sizes-20)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 20"
  },
  {
    "name": "sizes.24",
    "value": "var(--sizes-24)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 24"
  },
  {
    "name": "sizes.25",
    "value": "var(--sizes-25)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 25"
  },
  {
    "name": "sizes.28",
    "value": "var(--sizes-28)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 28"
  },
  {
    "name": "sizes.30",
    "value": "var(--sizes-30)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 30"
  },
  {
    "name": "sizes.32",
    "value": "var(--sizes-32)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 32"
  },
  {
    "name": "sizes.36",
    "value": "var(--sizes-36)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 36"
  },
  {
    "name": "sizes.40",
    "value": "var(--sizes-40)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 40"
  },
  {
    "name": "sizes.44",
    "value": "var(--sizes-44)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 44"
  },
  {
    "name": "sizes.45",
    "value": "var(--sizes-45)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 45"
  },
  {
    "name": "sizes.48",
    "value": "var(--sizes-48)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 48"
  },
  {
    "name": "sizes.50",
    "value": "var(--sizes-50)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 50"
  },
  {
    "name": "sizes.52",
    "value": "var(--sizes-52)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 52"
  },
  {
    "name": "sizes.56",
    "value": "var(--sizes-56)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 56"
  },
  {
    "name": "sizes.60",
    "value": "var(--sizes-60)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 60"
  },
  {
    "name": "sizes.64",
    "value": "var(--sizes-64)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 64"
  },
  {
    "name": "sizes.65",
    "value": "var(--sizes-65)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 65"
  },
  {
    "name": "sizes.72",
    "value": "var(--sizes-72)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 72"
  },
  {
    "name": "sizes.74",
    "value": "var(--sizes-74)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 74"
  },
  {
    "name": "sizes.75",
    "value": "var(--sizes-75)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 75"
  },
  {
    "name": "sizes.80",
    "value": "var(--sizes-80)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 80"
  },
  {
    "name": "sizes.90",
    "value": "var(--sizes-90)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 90"
  },
  {
    "name": "sizes.95",
    "value": "var(--sizes-95)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 95"
  },
  {
    "name": "sizes.96",
    "value": "var(--sizes-96)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 96"
  },
  {
    "name": "sizes.100",
    "value": "var(--sizes-100)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 100"
  },
  {
    "name": "sizes.120",
    "value": "var(--sizes-120)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 120"
  },
  {
    "name": "sizes.125",
    "value": "var(--sizes-125)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 125"
  },
  {
    "name": "sizes.140",
    "value": "var(--sizes-140)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 140"
  },
  {
    "name": "sizes.150",
    "value": "var(--sizes-150)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 150"
  },
  {
    "name": "sizes.160",
    "value": "var(--sizes-160)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 160"
  },
  {
    "name": "sizes.180",
    "value": "var(--sizes-180)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 180"
  },
  {
    "name": "sizes.220",
    "value": "var(--sizes-220)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 220"
  },
  {
    "name": "sizes.225",
    "value": "var(--sizes-225)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 225"
  },
  {
    "name": "sizes.300",
    "value": "var(--sizes-300)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 300"
  },
  {
    "name": "sizes.360",
    "value": "var(--sizes-360)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 360"
  },
  {
    "name": "sizes.0.25",
    "value": "var(--sizes-0.25)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 0-25"
  },
  {
    "name": "sizes.0.5",
    "value": "var(--sizes-0.5)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 0-5"
  },
  {
    "name": "sizes.0.75",
    "value": "var(--sizes-0.75)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 0-75"
  },
  {
    "name": "sizes.1.25",
    "value": "var(--sizes-1.25)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 1-25"
  },
  {
    "name": "sizes.1.5",
    "value": "var(--sizes-1.5)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 1-5"
  },
  {
    "name": "sizes.1.75",
    "value": "var(--sizes-1.75)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 1-75"
  },
  {
    "name": "sizes.2.25",
    "value": "var(--sizes-2.25)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 2-25"
  },
  {
    "name": "sizes.2.5",
    "value": "var(--sizes-2.5)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 2-5"
  },
  {
    "name": "sizes.3.5",
    "value": "var(--sizes-3.5)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 3-5"
  },
  {
    "name": "sizes.4.5",
    "value": "var(--sizes-4.5)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 4-5"
  },
  {
    "name": "sizes.5.5",
    "value": "var(--sizes-5.5)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 5-5"
  },
  {
    "name": "sizes.7.5",
    "value": "var(--sizes-7.5)",
    "type": "spacing",
    "displayName": "Beam / Sizes / 7-5"
  },
  {
    "name": "lineHeights.none",
    "value": "var(--line-heights-none)",
    "type": "line-height",
    "displayName": "Beam / Line height / none"
  },
  {
    "name": "lineHeights.tight",
    "value": "var(--line-heights-tight)",
    "type": "line-height",
    "displayName": "Beam / Line height / tight"
  },
  {
    "name": "lineHeights.snug",
    "value": "var(--line-heights-snug)",
    "type": "line-height",
    "displayName": "Beam / Line height / snug"
  },
  {
    "name": "lineHeights.normal",
    "value": "var(--line-heights-normal)",
    "type": "line-height",
    "displayName": "Beam / Line height / normal"
  },
  {
    "name": "lineHeights.relaxed",
    "value": "var(--line-heights-relaxed)",
    "type": "line-height",
    "displayName": "Beam / Line height / relaxed"
  },
  {
    "name": "lineHeights.loose",
    "value": "var(--line-heights-loose)",
    "type": "line-height",
    "displayName": "Beam / Line height / loose"
  },
  {
    "name": "colors.bg.page",
    "value": "var(--colors-bg.page)",
    "type": "color",
    "displayName": "Beam / Semantic / Bg / Page"
  },
  {
    "name": "colors.bg.card",
    "value": "var(--colors-bg.card)",
    "type": "color",
    "displayName": "Beam / Semantic / Bg / Card"
  },
  {
    "name": "colors.bg.nav",
    "value": "var(--colors-bg.nav)",
    "type": "color",
    "displayName": "Beam / Semantic / Bg / Nav"
  },
  {
    "name": "colors.text.primary",
    "value": "var(--colors-text.primary)",
    "type": "color",
    "displayName": "Beam / Semantic / Text / Primary"
  },
  {
    "name": "colors.text.secondary",
    "value": "var(--colors-text.secondary)",
    "type": "color",
    "displayName": "Beam / Semantic / Text / Secondary"
  },
  {
    "name": "colors.text.muted",
    "value": "var(--colors-text.muted)",
    "type": "color",
    "displayName": "Beam / Semantic / Text / Muted"
  },
  {
    "name": "colors.border.default",
    "value": "var(--colors-border.default)",
    "type": "color",
    "displayName": "Beam / Semantic / Border / Default"
  },
  {
    "name": "colors.border.subtle",
    "value": "var(--colors-border.subtle)",
    "type": "color",
    "displayName": "Beam / Semantic / Border / Subtle"
  },
  {
    "name": "colors.accent",
    "value": "var(--colors-accent)",
    "type": "color",
    "displayName": "Beam / Semantic / Accent"
  },
  {
    "name": "colors.sectionLabel",
    "value": "var(--colors-section-label)",
    "type": "color",
    "displayName": "Beam / Semantic / SectionLabel"
  }
] as const;

for (const t of beamTokens) {
  registerToken(t);
}
