import { css, cx } from "../../system.ts";

import { type ReactNode, useEffect, useMemo, useState } from "react";
import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkGfm from "remark-gfm";
import remarkRehype from "remark-rehype";
import rehypeRaw from "rehype-raw";
import rehypeSanitize from "rehype-sanitize";
import rehypeStringify from "rehype-stringify";
import { useTheme } from "../../hooks/use-theme.ts";

/** Props for {@link MarkdownRenderer}. */
export interface MarkdownRendererProps {
  /** Markdown source string (CommonMark + GitHub Flavored Markdown). Supports inline/block LaTeX with `$...$` (inline) and `$$...$$` (display). */
  content: string;
  /** Optional CSS class for the wrapper div. */
  className?: string;
}

const processor = unified()
  .use(remarkParse)
  .use(remarkGfm)
  .use(remarkRehype, { allowDangerousHtml: true })
  .use(rehypeRaw)
  .use(rehypeSanitize)
  .use(rehypeStringify);

type KatexType = typeof import("katex").default;

let katexModule: KatexType | null = null;
let katexLoading = false;
const katexCallbacks: (() => void)[] = [];

function loadKatex(): Promise<KatexType> {
  if (katexModule) return Promise.resolve(katexModule);
  return new Promise((resolve) => {
    katexCallbacks.push(() => resolve(katexModule as KatexType));
    if (!katexLoading) {
      katexLoading = true;
      Promise.all([
        import("katex"),
        // deno-lint-ignore no-explicit-any
        import("katex/dist/katex.min.css" as any),
      ]).then(([mod]) => {
        katexModule = mod.default as KatexType;
        katexCallbacks.forEach((cb) => cb());
        katexCallbacks.length = 0;
      });
    }
  });
}

/** Extract math blocks, replace with text markers that survive sanitization */
function extractMath(
  md: string,
): {
  processed: string;
  blocks: { id: string; math: string; display: boolean }[];
} {
  const blocks: { id: string; math: string; display: boolean }[] = [];
  let idx = 0;

  // Block math: $$...$$
  let processed = md.replace(/\$\$([\s\S]+?)\$\$/g, (_, math) => {
    const id = `BEAMMATH${idx++}BEAMMATH`;
    blocks.push({ id, math: math.trim(), display: true });
    return id;
  });

  // Inline math: $...$  (not preceded/followed by $)
  processed = processed.replace(
    /(?<!\$)\$(?!\$)(.+?)(?<!\$)\$(?!\$)/g,
    (_, math) => {
      const id = `BEAMMATH${idx++}BEAMMATH`;
      blocks.push({ id, math: math.trim(), display: false });
      return id;
    },
  );

  return { processed, blocks };
}

/**
 * Renders CommonMark + GitHub Flavored Markdown with sanitization and LaTeX math support.
 * Converts markdown to HTML via a unified pipeline (remark → rehype → sanitize).
 * LaTeX blocks (`$$...$$`) and inline math (`$...$`) are lazily loaded and rendered with KaTeX.
 *
 * @example
 * ```tsx
 * <MarkdownRenderer content="# Hello\n\n$E = mc^2$" />
 * ```
 */
export function MarkdownRenderer(
  { content, className }: MarkdownRendererProps,
): ReactNode {
  const { theme } = useTheme();
  const [katex, setKatex] = useState<KatexType | null>(null);

  useEffect(() => {
    // Check if content has math before loading KaTeX
    if (/\$/.test(content)) {
      loadKatex().then(setKatex);
    }
  }, [content]);

  const html = useMemo(() => {
    try {
      const { processed, blocks } = extractMath(content);
      let result = String(processor.processSync(processed));

      // Replace text markers with KaTeX-rendered HTML
      // SECURITY: KaTeX.renderToString produces safe math markup from LaTeX
      // input only — it does not pass through arbitrary HTML.
      for (const block of blocks) {
        let rendered: string;
        if (katex) {
          try {
            rendered = katex.renderToString(block.math, {
              displayMode: block.display,
              throwOnError: false,
            });
          } catch {
            rendered = `<code>${block.math}</code>`;
          }
        } else {
          rendered = `<code>${block.math}</code>`;
        }

        if (block.display) {
          // Block math: unwrap from <p> tag and use a <div> wrapper
          const wrapped = `<div class="beam-math-display">${rendered}</div>`;
          result = result.replace(
            new RegExp(`<p>\\s*${block.id}\\s*</p>`),
            wrapped,
          );
          // Fallback if not wrapped in <p>
          result = result.replace(block.id, wrapped);
        } else {
          result = result.replace(block.id, rendered);
        }
      }

      return result;
    } catch {
      return `<pre>${content}</pre>`;
    }
  }, [content, katex]);

  /*
   * SECURITY NOTE: The HTML rendered here is produced by the unified pipeline
   * which includes rehype-sanitize. Math markup is injected after sanitization
   * but is generated by KaTeX.renderToString which only processes LaTeX notation.
   */
  return (
    <div
      className={cx(
        wrapperStyle,
        theme === "dark" ? darkOverrides : undefined,
        className,
      )}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

/* ------------------------------------------------------------------ */
/* Scoped styles for rendered markdown                                 */
/* ------------------------------------------------------------------ */

const wrapperStyle = css({
  fontSize: "15",
  lineHeight: 1.7,
  color: "text.primary",
  wordBreak: "break-word",

  /* Headings */
  "& h1, & h2, & h3, & h4, & h5, & h6": {
    fontWeight: "heading",
    color: "text.primary",
    scrollMarginTop: "20",
    marginTop: "8",
    marginBottom: "4",
    lineHeight: 1.3,
  },
  "& h1": { fontSize: "3xl", letterSpacing: "-0.02em" },
  "& h2": {
    fontSize: "2xl",
    letterSpacing: "-0.01em",
    borderBottomWidth: "0.25",
    borderBottomStyle: "solid",
    borderColor: "border.default",
    paddingBottom: "2",
  },
  "& h3": { fontSize: "xl" },
  "& h4": { fontSize: "md" },

  /* Paragraphs */
  "& p": { marginBottom: "4" },

  /* Links — distinguishable by color AND underline for 508 */
  "& a": {
    color: "sunbeam.orange",
    textDecoration: "underline",
    textUnderlineOffset: "0.5",
    _hover: { opacity: 0.8 },
  },

  /* Bold / italic */
  "& strong": { fontWeight: "bold" },
  "& em": { fontStyle: "italic" },

  /* Code blocks (pre > code) */
  "& pre": {
    backgroundColor: "bg.card",
    borderWidth: "0.25",
    borderStyle: "solid",
    borderColor: "border.default",
    padding: "4",
    overflowX: "auto",
    marginBottom: "4",
    borderRadius: "0",
  },
  "& pre code": {
    fontFamily: "mono",
    fontSize: "13",
    lineHeight: 1.6,
    background: "none",
    padding: "0",
    border: "none",
  },

  /* Inline code */
  "& :not(pre) > code": {
    fontFamily: "mono",
    fontSize: "13",
    backgroundColor: "bg.card",
    py: "0.5",
    px: "1.5",
    borderWidth: "0.25",
    borderStyle: "solid",
    borderColor: "border.default",
  },

  /* Blockquotes */
  "& blockquote": {
    borderLeftWidth: "0.75",
    borderLeftStyle: "solid",
    borderColor: "sunbeam.orange",
    paddingLeft: "4",
    marginLeft: "0",
    marginBottom: "4",
    color: "text.secondary",
    fontStyle: "italic",
  },

  /* Lists */
  "& ul, & ol": {
    paddingLeft: "6",
    marginBottom: "4",
  },
  "& li": { marginBottom: "1" },

  /* Task lists (GFM checkboxes) */
  "& ul.contains-task-list": {
    listStyle: "none",
    paddingLeft: "0",
  },
  "& li.task-list-item": {
    display: "flex",
    alignItems: "baseline",
    gap: "2",
  },
  '& input[type="checkbox"]': {
    accentColor: "var(--colors-sunbeam-orange)",
    width: "3.5",
    height: "3.5",
    flexShrink: 0,
  },

  /* Tables */
  "& table": {
    width: "100%",
    borderCollapse: "collapse",
    marginBottom: "4",
    fontSize: "sm",
  },
  "& th": {
    textAlign: "left",
    fontWeight: "button",
    fontSize: "2xs",
    textTransform: "uppercase",
    letterSpacing: "0.15em",
    color: "text.muted",
    backgroundColor: "bg.card",
    py: "2.5",
    px: "3",
    borderBottomWidth: "0.25",
    borderBottomStyle: "solid",
    borderColor: "border.default",
  },
  "& td": {
    py: "2.5",
    px: "3",
    borderBottomWidth: "0.25",
    borderBottomStyle: "solid",
    borderColor: "border.default",
    color: "text.primary",
  },
  "& tr:last-child td": {
    borderBottom: "none",
  },

  /* Images */
  "& img": {
    maxWidth: "100%",
    height: "auto",
    marginBottom: "4",
  },

  /* Horizontal rule */
  "& hr": {
    border: "none",
    borderTopWidth: "0.25",
    borderTopStyle: "solid",
    borderColor: "border.default",
    my: "8",
    mx: "0",
  },

  /* Delete / strikethrough */
  "& del": {
    textDecoration: "line-through",
    color: "text.muted",
  },

  /* KaTeX display math */
  "& .beam-math-display": {
    textAlign: "center",
    marginBottom: "4",
    overflowX: "auto",
  },

  /* KaTeX inline math — prevent line-height disruption */
  "& .katex": {
    fontSize: "1em",
  },
});

const darkOverrides = css({
  /* No additional overrides needed — Beam tokens handle dark mode via CSS vars */
});
