/**
 * Generates app/src/plasmic/tokens.generated.ts — Plasmic Studio token
 * registrations derived from beamPreset.
 *
 * Values are registered as CSS variable references (var(--...)) taken from
 * the Panda token artifacts in styled-system/tokens, so dark mode
 * ([data-theme=dark]) resolves in CSS and Plasmic designs stay theme-aware.
 *
 * Plasmic token types are limited to: color, spacing, font-size, line-height,
 * opacity, font-family. Panda categories with no Plasmic equivalent (radii,
 * shadows, fontWeights, breakpoints) are intentionally skipped — see
 * docs/plasmic-app-host-scope.md §3.
 */
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { beamPreset } from "../../packages/beam-ui/src/preset";

const require = createRequire(import.meta.url);
const { token } = require("../styled-system/tokens/index.mjs");

type PlasmicTokenType = "color" | "spacing" | "font-size" | "line-height" | "font-family";

const CATEGORY_MAP: Record<string, PlasmicTokenType> = {
  colors: "color",
  spacing: "spacing",
  sizes: "spacing",
  fontSizes: "font-size",
  fonts: "font-family",
  lineHeights: "line-height",
};

interface Registration {
  name: string;
  value: string;
  type: PlasmicTokenType;
  displayName: string;
}

function humanize(path: string, semantic: boolean): string {
  const parts = path.split(".").slice(1).map((p) => p.charAt(0).toUpperCase() + p.slice(1));
  return ["Beam", ...(semantic ? ["Semantic"] : []), ...parts].join(" / ");
}

function collect(
  category: string,
  entries: Record<string, unknown> | undefined,
  semantic: boolean,
  out: Registration[],
) {
  const type = CATEGORY_MAP[category];
  if (!type || !entries) return;
  for (const name of Object.keys(entries)) {
    const path = `${category}.${name}`;
    const variable: string | undefined = token.var(path);
    if (!variable) {
      console.warn(`  ⚠ no CSS variable for token ${path}, skipping`);
      continue;
    }
    out.push({ name: path, value: variable, type, displayName: humanize(path, semantic) });
  }
}

const theme = (beamPreset.theme ?? {}) as {
  extend?: {
    tokens?: Record<string, Record<string, unknown>>;
    semanticTokens?: Record<string, Record<string, unknown>>;
  };
};

const registrations: Registration[] = [];
for (const [category, entries] of Object.entries(theme.extend?.tokens ?? {})) {
  collect(category, entries, false, registrations);
}
for (const [category, entries] of Object.entries(theme.extend?.semanticTokens ?? {})) {
  collect(category, entries, true, registrations);
}

const output = `// AUTO-GENERATED by scripts/generate-plasmic-tokens.ts — do not edit.
// Regenerated on every dev/build start from beamPreset (see vite.config.ts).
import { registerToken } from "@plasmicapp/react-web/lib/host";

const beamTokens = ${JSON.stringify(registrations, null, 2)} as const;

for (const t of beamTokens) {
  registerToken(t);
}
`;

writeFileSync(new URL("../src/plasmic/tokens.generated.ts", import.meta.url), output);
console.log(`  wrote tokens.generated.ts (${registrations.length} Plasmic tokens)`);
